/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MocksRouteImport } from './routes/mocks'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMentorRouteImport } from './routes/api/mentor'

const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksRoute = MocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRoute = ApiMentorRouteImport.update({
  id: '/api/mentor',
  path: '/api/mentor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/practice': typeof PracticeRoute
  '/revision': typeof RevisionRoute
  '/api/mentor': typeof ApiMentorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/practice': typeof PracticeRoute
  '/revision': typeof RevisionRoute
  '/api/mentor': typeof ApiMentorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/focus': typeof FocusRoute
  '/mentor': typeof MentorRoute
  '/mistakes': typeof MistakesRoute
  '/mocks': typeof MocksRoute
  '/practice': typeof PracticeRoute
  '/revision': typeof RevisionRoute
  '/api/mentor': typeof ApiMentorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/focus'
    | '/mentor'
    | '/mistakes'
    | '/mocks'
    | '/practice'
    | '/revision'
    | '/api/mentor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/focus'
    | '/mentor'
    | '/mistakes'
    | '/mocks'
    | '/practice'
    | '/revision'
    | '/api/mentor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/focus'
    | '/mentor'
    | '/mistakes'
    | '/mocks'
    | '/practice'
    | '/revision'
    | '/api/mentor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FocusRoute: typeof FocusRoute
  MentorRoute: typeof MentorRoute
  MistakesRoute: typeof MistakesRoute
  MocksRoute: typeof MocksRoute
  PracticeRoute: typeof PracticeRoute
  RevisionRoute: typeof RevisionRoute
  ApiMentorRoute: typeof ApiMentorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks': {
      id: '/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof MocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor': {
      id: '/api/mentor'
      path: '/api/mentor'
      fullPath: '/api/mentor'
      preLoaderRoute: typeof ApiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FocusRoute: FocusRoute,
  MentorRoute: MentorRoute,
  MistakesRoute: MistakesRoute,
  MocksRoute: MocksRoute,
  PracticeRoute: PracticeRoute,
  RevisionRoute: RevisionRoute,
  ApiMentorRoute: ApiMentorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
